#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

console.log('🚀 OSCAR BROOME REVENUE - Production Deployment Script');
console.log('====================================================\n');

// Configuration
const CONFIG = {
  requiredEnvVars: [
    'STRIPE_SECRET_KEY',
    'SMTP_HOST',
    'SMTP_USER',
    'SMTP_PASS',
    'TWILIO_ACCOUNT_SID',
    'TWILIO_AUTH_TOKEN',
    'TWILIO_PHONE_NUMBER'
  ],
  optionalEnvVars: [
    'NODE_ENV',
    'PORT',
    'SMTP_PORT'
  ],
  productionDefaults: {
    NODE_ENV: 'production',
    PORT: '3000',
    SMTP_PORT: '587'
  }
};

class ProductionDeployer {
  constructor() {
    this.errors = [];
    this.warnings = [];
  }

  log(message, type = 'info') {
    const timestamp = new Date().toISOString();
    const prefix = {
      info: 'ℹ️ ',
      success: '✅ ',
      warning: '⚠️ ',
      error: '❌ ',
      step: '🔧 '
    }[type] || '📝 ';

    console.log(`[${timestamp}] ${prefix}${message}`);
  }

  async run() {
    try {
      this.log('Starting production deployment process...', 'step');

      await this.checkEnvironment();
      await this.validateDependencies();
      await this.setupEnvironment();
      await this.validateConfiguration();
      await this.runPreFlightChecks();
      await this.startProductionServer();

      this.log('Production deployment completed successfully!', 'success');

    } catch (error) {
      this.log(`Deployment failed: ${error.message}`, 'error');
      this.errors.push(error.message);
      process.exit(1);
    }
  }

  async checkEnvironment() {
    this.log('Checking system environment...', 'step');

    // Check Node.js version
    const nodeVersion = process.version;
    this.log(`Node.js version: ${nodeVersion}`);

    if (!nodeVersion.startsWith('v14.') && !nodeVersion.startsWith('v16.') && !nodeVersion.startsWith('v18.') && !nodeVersion.startsWith('v20.')) {
      throw new Error(`Unsupported Node.js version: ${nodeVersion}. Please use Node.js 14, 16, 18, or 20.`);
    }

    // Check if we're in the right directory
    if (!fs.existsSync('package.json')) {
      throw new Error('package.json not found. Please run this script from the project root directory.');
    }

    // Check if merchant_bill_pay.js exists
    if (!fs.existsSync('earnings_dashboard/merchant_bill_pay.js')) {
      throw new Error('merchant_bill_pay.js not found. Please ensure the merchant bill pay system is properly installed.');
    }

    this.log('System environment check passed', 'success');
  }

  async validateDependencies() {
    this.log('Validating dependencies...', 'step');

    try {
      // Check if node_modules exists
      if (!fs.existsSync('node_modules')) {
        this.log('Installing dependencies...', 'step');
        execSync('npm install', { stdio: 'inherit' });
      }

      // Validate critical dependencies
      const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8'));
      const requiredDeps = ['express', 'stripe', 'nodemailer', 'twilio', 'dotenv'];

      for (const dep of requiredDeps) {
        if (!packageJson.dependencies[dep]) {
          throw new Error(`Required dependency '${dep}' not found in package.json`);
        }
      }

      this.log('Dependencies validation passed', 'success');

    } catch (error) {
      throw new Error(`Dependency validation failed: ${error.message}`);
    }
  }

  async setupEnvironment() {
    this.log('Setting up production environment...', 'step');

    // Create .env file if it doesn't exist
    if (!fs.existsSync('.env')) {
      this.log('Creating .env file from template...', 'step');

      let envContent = '# Production Environment Variables\n';
      envContent += '# Generated by production_deploy.js\n\n';

      // Add production defaults
      Object.entries(CONFIG.productionDefaults).forEach(([key, value]) => {
        envContent += `${key}=${value}\n`;
      });

      // Add placeholders for required variables
      CONFIG.requiredEnvVars.forEach(varName => {
        if (!CONFIG.productionDefaults[varName]) {
          envContent += `# ${varName}=your_${varName.toLowerCase()}_here\n`;
        }
      });

      fs.writeFileSync('.env', envContent);
      this.log('.env file created. Please configure your credentials.', 'warning');
    }

    // Create logs directory
    if (!fs.existsSync('logs')) {
      fs.mkdirSync('logs');
      this.log('Logs directory created');
    }

    this.log('Environment setup completed', 'success');
  }

  async validateConfiguration() {
    this.log('Validating configuration...', 'step');

    // Load environment variables
    require('dotenv').config();

    let missingRequired = [];
    let missingOptional = [];

    // Check required environment variables
    CONFIG.requiredEnvVars.forEach(varName => {
      if (!process.env[varName] || process.env[varName].startsWith('your_')) {
        missingRequired.push(varName);
      }
    });

    // Check optional environment variables
    CONFIG.optionalEnvVars.forEach(varName => {
      if (!process.env[varName]) {
        missingOptional.push(varName);
      }
    });

    if (missingRequired.length > 0) {
      this.log(`Missing required environment variables: ${missingRequired.join(', ')}`, 'error');
      this.log('Please configure these variables in your .env file', 'warning');
      this.log('You can use the setup_credentials.js script to configure them interactively', 'info');
    }

    if (missingOptional.length > 0) {
      this.log(`Missing optional environment variables (using defaults): ${missingOptional.join(', ')}`, 'warning');
    }

    if (missingRequired.length === 0) {
      this.log('Configuration validation passed', 'success');
    } else {
      this.warnings.push('Some required configuration is missing');
    }
  }

  async runPreFlightChecks() {
    this.log('Running pre-flight checks...', 'step');

    try {
      // Test module imports
      const merchantBillPay = require('./earnings_dashboard/merchant_bill_pay');
      this.log('Merchant bill pay module loaded successfully');

      // Check if all required functions exist
      const requiredFunctions = [
        'createMerchantPaymentIntent',
        'handleMerchantWebhook',
        'sendMerchantPaymentSuccessNotification',
        'sendMerchantPaymentFailureNotification',
        'sendSMSNotification',
        'getMerchantEmail',
        'getMerchantPhone'
      ];

      let missingFunctions = [];
      requiredFunctions.forEach(funcName => {
        if (typeof merchantBillPay[funcName] !== 'function') {
          missingFunctions.push(funcName);
        }
      });

      if (missingFunctions.length > 0) {
        throw new Error(`Missing required functions: ${missingFunctions.join(', ')}`);
      }

      this.log('All required functions are available', 'success');

      // Test merchant data
      const testMerchant = merchantBillPay.getMerchantEmail('merchant_001');
      if (testMerchant) {
        this.log('Merchant data loaded successfully');
      } else {
        this.log('Merchant data not found - using mock data', 'warning');
      }

    } catch (error) {
      throw new Error(`Pre-flight check failed: ${error.message}`);
    }

    this.log('Pre-flight checks completed', 'success');
  }

  async startProductionServer() {
    this.log('Starting production server...', 'step');

    const port = process.env.PORT || 3000;
    const nodeEnv = process.env.NODE_ENV || 'production';

    this.log(`Environment: ${nodeEnv}`);
    this.log(`Port: ${port}`);

    // Check if port is available
    const net = require('net');
    const server = net.createServer();

    return new Promise((resolve, reject) => {
      server.listen(port, (err) => {
        server.close();

        if (err) {
          reject(new Error(`Port ${port} is not available`));
          return;
        }

        this.log(`Port ${port} is available`, 'success');

        // Start the server
        this.log('Starting server with PM2...', 'step');

        try {
          // Check if PM2 is available
          execSync('pm2 --version', { stdio: 'pipe' });

          // Use PM2 for production
          execSync('pm2 stop oscar-broome-revenue || true', { stdio: 'pipe' });
          execSync('pm2 delete oscar-broome-revenue || true', { stdio: 'pipe' });
          execSync('pm2 start server-enhanced.js --name oscar-broome-revenue', { stdio: 'inherit' });
          execSync('pm2 save', { stdio: 'pipe' });

          this.log('Server started with PM2 process manager', 'success');
          this.log('Use "pm2 logs oscar-broome-revenue" to view logs', 'info');
          this.log('Use "pm2 monit" to monitor the application', 'info');

        } catch (pm2Error) {
          this.log('PM2 not available, starting server directly...', 'warning');

          // Fallback to direct node execution
          const { spawn } = require('child_process');
          const serverProcess = spawn('node', ['server-enhanced.js'], {
            detached: true,
            stdio: 'ignore'
          });

          serverProcess.unref();
          this.log('Server started directly with Node.js', 'success');
          this.log(`Process ID: ${serverProcess.pid}`, 'info');
        }

        // Wait a moment for server to start
        setTimeout(() => {
          this.log(`🚀 Server should be running at http://localhost:${port}`, 'success');
          resolve();
        }, 2000);

      });
    });
  }

  showSummary() {
    console.log('\n📊 DEPLOYMENT SUMMARY');
    console.log('====================');

    if (this.errors.length > 0) {
      console.log('\n❌ ERRORS:');
      this.errors.forEach(error => console.log(`   - ${error}`));
    }

    if (this.warnings.length > 0) {
      console.log('\n⚠️  WARNINGS:');
      this.warnings.forEach(warning => console.log(`   - ${warning}`));
    }

    console.log('\n✅ COMPLETED STEPS:');
    console.log('   - Environment validation');
    console.log('   - Dependency installation');
    console.log('   - Configuration setup');
    console.log('   - Pre-flight checks');
    console.log('   - Production server startup');

    console.log('\n🔧 NEXT STEPS:');
    console.log('   1. Configure your production credentials in .env');
    console.log('   2. Set up SSL certificates for HTTPS');
    console.log('   3. Configure reverse proxy (nginx recommended)');
    console.log('   4. Set up monitoring and alerting');
    console.log('   5. Configure backup and recovery procedures');

    console.log('\n📝 USEFUL COMMANDS:');
    console.log('   - View logs: pm2 logs oscar-broome-revenue');
    console.log('   - Monitor: pm2 monit');
    console.log('   - Restart: pm2 restart oscar-broome-revenue');
    console.log('   - Stop: pm2 stop oscar-broome-revenue');
  }
}

// Run the deployment
const deployer = new ProductionDeployer();

deployer.run().then(() => {
  deployer.showSummary();
}).catch((error) => {
  console.error('\n💥 DEPLOYMENT FAILED');
  console.error('==================');
  console.error(error.message);
  process.exit(1);
});
