#!/usr/bin/env node

import { info, error, warn, debug } from 'utils/loggerWrapper.js';

const fs = require('fs');
const path = require('path');
const readline = require('readline');

logger.info('🔐 Merchant Bill Pay Credentials Setup');
logger.info('=====================================\n');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function askQuestion(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer);
    });
  });
}

function askPassword(question) {
  return new Promise((resolve) => {
    const stdin = process.stdin;
    const stdout = process.stdout;

    stdout.write(question);
    stdin.setRawMode(true);
    stdin.resume();
    stdin.setEncoding('utf8');

    let password = '';

    stdin.on('data', function (char) {
      char = char + '';

      switch (char) {
        case '\n':
        case '\r':
        case '\u0004':
          stdin.setRawMode(false);
          stdin.pause();
          stdout.write('\n');
          resolve(password);
          break;
        case '\u0003':
          process.exit();
          break;
        default:
          stdout.write('*');
          password += char;
          break;
      }
    });
  });
}

async function setupCredentials() {
  logger.info(
    'This script will help you set up your credentials for the Merchant Bill Pay system.\n'
  );

  const credentials = {};

  // Stripe Setup
  logger.info('1. 🚀 Stripe Configuration');
  logger.info(
    '   Get your API keys from: https://dashboard.stripe.com/apikeys\n'
  );

  credentials.STRIPE_SECRET_KEY = await askQuestion(
    '   Enter your Stripe Secret Key (sk_test_...): '
  );

  // Email Setup
  logger.info('\n2. 📧 Email Configuration');
  logger.info('   For Gmail: Use App Password (not your regular password)');
  logger.info('   Enable 2FA first, then generate App Password at:');
  logger.info('   https://myaccount.google.com/apppasswords\n');

  const emailProvider = await askQuestion('   Email provider (gmail/other): ');
  if (emailProvider.toLowerCase() === 'gmail') {
    credentials.SMTP_HOST = 'smtp.gmail.com';
    credentials.SMTP_PORT = '587';
    logger.info('   Using Gmail SMTP settings...');
  } else {
    credentials.SMTP_HOST = await askQuestion('   SMTP Host: ');
    credentials.SMTP_PORT = await askQuestion('   SMTP Port: ');
  }

  credentials.SMTP_USER = await askQuestion('   Email address: ');
  credentials.SMTP_PASS = await askPassword('   Password/App Password: ');

  // Twilio Setup
  logger.info('\n3. 📱 Twilio SMS Configuration');
  logger.info('   Get your credentials from: https://console.twilio.com\n');

  credentials.TWILIO_ACCOUNT_SID = await askQuestion(
    '   Account SID (AC...): '
  );
  credentials.TWILIO_AUTH_TOKEN = await askPassword('   Auth Token (SK...): ');
  credentials.TWILIO_PHONE_NUMBER = await askQuestion(
    '   Phone Number (+1...): '
  );

  // Create .env file
  logger.info('\n4. 📝 Creating .env file...');

  let envContent = '# 🔐 Merchant Bill Pay Environment Variables\n';
  envContent += '# Generated by setup_credentials.js\n\n';

  envContent += '# STRIPE CONFIGURATION\n';
  envContent += `STRIPE_SECRET_KEY=${credentials.STRIPE_SECRET_KEY}\n\n`;

  envContent += '# EMAIL CONFIGURATION\n';
  envContent += `SMTP_HOST=${credentials.SMTP_HOST}\n`;
  envContent += `SMTP_PORT=${credentials.SMTP_PORT}\n`;
  envContent += `SMTP_USER=${credentials.SMTP_USER}\n`;
  envContent += `SMTP_PASS=${credentials.SMTP_PASS}\n\n`;

  envContent += '# TWILIO CONFIGURATION\n';
  envContent += `TWILIO_ACCOUNT_SID=${credentials.TWILIO_ACCOUNT_SID}\n`;
  envContent += `TWILIO_AUTH_TOKEN=${credentials.TWILIO_AUTH_TOKEN}\n`;
  envContent += `TWILIO_PHONE_NUMBER=${credentials.TWILIO_PHONE_NUMBER}\n\n`;

  envContent += '# DEVELOPMENT SETTINGS\n';
  envContent += 'NODE_ENV=development\n';
  envContent += 'PORT=3000\n';

  try {
    fs.writeFileSync('.env', envContent);
    logger.info('✅ .env file created successfully!');
  } catch (error) {
    logger.error('❌ Error creating .env file:', error.message);
    rl.close();
    return;
  }

  // Test the setup
  logger.info('\n5. 🧪 Testing your configuration...');

  try {
    const testModule = require('./earnings_dashboard/merchant_bill_pay');
    logger.info('✅ Module loads successfully with your credentials!');
  } catch (error) {
    logger.info(
      '⚠️  Module loaded with warnings (this is normal for missing optional configs)'
    );
  }

  logger.info('\n🎉 Setup Complete!');
  logger.info('\n📋 Next Steps:');
  logger.info('1. Review your .env file to ensure all credentials are correct');
  logger.info(
    '2. Run the comprehensive test: node comprehensive_merchant_test.js'
  );
  logger.info('3. Start your application with the new credentials');
  logger.info('\n🔒 Security Reminder:');
  logger.info('- Never commit .env files to version control');
  logger.info('- Use test keys for development');
  logger.info('- Rotate credentials regularly');

  rl.close();
}

setupCredentials().catch(console.error);
