name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Lint code
      run: |
        pip install flake8
        flake8 .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to server
      run: |
        echo "Starting deployment..."
        # Example: Deploy to a remote server via SSH
        ssh user@yourserver.com << 'EOF'
          cd /path/to/your/app
          git pull origin main
          # Restart the application service, e.g., systemctl restart yourapp
          systemctl restart yourapp
        EOF
        echo "Deployment completed."
