name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Lint code
      run: |
        pip install flake8
        flake8 .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t equity-shield-advocates:latest .

    - name: Tag Docker image
      run: |
        docker tag equity-shield-advocates:latest ${{ secrets.DOCKER_USERNAME }}/equity-shield-advocates:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/equity-shield-advocates:latest

    - name: Deploy to server
      run: |
        echo "Starting deployment..."
        ssh user@yourserver.com << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/equity-shield-advocates:latest
          docker stop equity-shield-advocates || true
          docker rm equity-shield-advocates || true
          docker run -d -p 8000:8000 --name equity-shield-advocates ${{ secrets.DOCKER_USERNAME }}/equity-shield-advocates:latest
        EOF
        echo "Deployment completed."
